### ISSUE TITLE
(feat) Implement UI Kitten Library

### ISSUE THREAD

**Issue by jaxcksn** [ttugdsc/raiderride-FUBU#6]
**Is your feature request related to a problem? Please describe.**
Using a UI Library allows for more learning from contributors and allows more people to contribute to the project.

**Describe the solution you'd like**
Implement, Theme, and Brand the UI Kitten Library

**Describe alternatives you've considered**
React Native UI (Although I think UI Kitten looks better).

**Additional context**
Will probably be implemented in the same PR as #5, I'm just opening a separate issue for it. Edit: Forgot to add that I looked into it, and we might have to extend one of the UI Kitten components to create a location picker, but we can get to that once it's needed.

**Comment by Guysnacho** [comment]
Run it, I'd like to help if you feel like there's a need. If not imma start on other pages.
